# Generated by Django 5.2.5 on 2025-08-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(max_length=8, unique=True)),
                ('party_name', models.CharField(max_length=64, unique=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_fips', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_code', models.CharField(max_length=2, unique=True)),
                ('state_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_fips', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=128)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us_elections.state')),
            ],
            options={
                'unique_together': {('state', 'county_name')},
            },
        ),
        migrations.CreateModel(
            name='CountyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('candidate_votes', models.IntegerField()),
                ('total_votes', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='us_elections.candidate')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us_elections.county')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='us_elections.party')),
            ],
            options={
                'unique_together': {('year', 'county', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='StateResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('candidate_votes', models.IntegerField()),
                ('total_votes', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='us_elections.candidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='us_elections.party')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us_elections.state')),
            ],
            options={
                'unique_together': {('year', 'state', 'candidate')},
            },
        ),
    ]
