# Generated by Django 5.2.5 on 2025-08-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_code',
        ),
    ]
