# Generated by Django 5.2.5 on 2025-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_elections', '0002_remove_party_party_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_name',
        ),
        migrations.AddField(
            model_name='party',
            name='party',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
