# Generated by Django 5.2.5 on 2025-08-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_elections', '0003_remove_party_party_name_party_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='county',
            unique_together=set(),
        ),
    ]
